import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { parseVoucherSecret, voucherCanonicalBytes, VOUCHER_TAGS } from '../src/secret.js';

/**
 * The load-bearing test in this file is the golden vector.
 *
 * The issuer signature covers a canonical rendering of the secret, so the
 * TypeScript renderer and the Java one in `cashu-voucher` must agree
 * byte-for-byte. Reading both and judging them equivalent is not evidence: the
 * failure mode is a signature that verifies over content the issuer did not
 * mean, and that is invisible to inspection.
 *
 * So the vector below was *generated* by running `VoucherCanonicalBytes.of()`
 * in the cashu-voucher repo against a secret exercising every case that has
 * ever differed between the two: a numeric tag (written bare), a string tag
 * that looks numeric, the P2PK tags a `P2PKVoucherSecret` carries implicitly,
 * the `issuer_sig`/`issuer_pubkey` exclusion, non-ASCII, and every JSON escape.
 *
 * Regenerate with `GoldenVectorGen` in cashu-voucher if the wire format changes
 * — but a change here that is not accompanied by a mint change is a bug, not a
 * rebase.
 */
const GOLDEN_SECRET_JSON =
  '["P2PK_VOUCHER",{"nonce":"0123456789abcdef","data":"02aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","tags":[["n_sigs","1"],["sigflag","SIG_INPUTS"],["voucher_id","v-123"],["issuer","imani"],["unit","sat"],["face_value","1000"],["expires_at","2000000000"],["merchant_metadata","café \\"quoted\\"\\nline\\tsep\\\\back"],["issuer_pubkey","deadbeef"],["issuer_sig","ffff"]]}]';

const GOLDEN_CANONICAL_HEX =
  '5b225032504b5f564f5543484552222c22303261616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161222c2230313233343536373839616263646566222c5b5b226e5f73696773222c2231225d2c5b22736967666c6167222c225349475f494e50555453225d2c5b22766f75636865725f6964222c22762d313233225d2c5b22697373756572222c22696d616e69225d2c5b22756e6974222c22736174225d2c5b22666163655f76616c7565222c313030305d2c5b22657870697265735f6174222c323030303030303030305d2c5b226d65726368616e745f6d65746164617461222c22636166c3a9205c2271756f7465645c225c6e6c696e655c747365705c5c6261636b225d5d5d';

const toHex = (bytes: Uint8Array): string =>
  Array.from(bytes, (byte) => byte.toString(16).padStart(2, '0')).join('');

describe('canonical bytes match the Java issuer', () => {
  it('reproduces a vector generated by cashu-voucher VoucherCanonicalBytes', () => {
    const parsed = parseVoucherSecret(GOLDEN_SECRET_JSON);

    expect(parsed).not.toBeNull();
    expect(toHex(voucherCanonicalBytes(parsed!))).toBe(GOLDEN_CANONICAL_HEX);
  });

  it('writes numeric tags bare and string tags quoted, keyed on the tag name', () => {
    // `face_value` is numeric so `1000` is written bare; `voucher_id` is not,
    // so a value that happens to look numeric stays quoted. Keying on the
    // runtime type instead would make these two indistinguishable.
    const parsed = parseVoucherSecret(
      JSON.stringify([
        'P2PK_VOUCHER',
        { nonce: 'n', data: '02ab', tags: [[VOUCHER_TAGS.FACE_VALUE, '1000'], [VOUCHER_TAGS.VOUCHER_ID, '1000']] },
      ])
    );

    expect(new TextDecoder().decode(voucherCanonicalBytes(parsed!))).toBe(
      '["P2PK_VOUCHER","02ab","n",[["face_value",1000],["voucher_id","1000"]]]'
    );
  });

  it('excludes the signature tags, which cannot be covered by the signature', () => {
    const withSig = parseVoucherSecret(
      JSON.stringify([
        'P2PK_VOUCHER',
        {
          nonce: 'n',
          data: '02ab',
          tags: [[VOUCHER_TAGS.ISSUER, 'imani'], [VOUCHER_TAGS.ISSUER_PUBKEY, 'dead'], [VOUCHER_TAGS.ISSUER_SIG, 'beef']],
        },
      ])
    );
    const withoutSig = parseVoucherSecret(
      JSON.stringify(['P2PK_VOUCHER', { nonce: 'n', data: '02ab', tags: [[VOUCHER_TAGS.ISSUER, 'imani']] }])
    );

    expect(toHex(voucherCanonicalBytes(withSig!))).toBe(toHex(voucherCanonicalBytes(withoutSig!)));
  });

  it('commits to the kind, so an unlocked signature does not transfer to a locked voucher', () => {
    // The Java renderer used to hardcode "VOUCHER". If it still did, these two
    // would be identical and an issuer's attestation for an unlocked voucher
    // would verify against a P2PK-locked one carrying the same metadata --
    // meaning the lock was covered by nothing the issuer said.
    const body = { nonce: 'n', data: '02ab', tags: [[VOUCHER_TAGS.ISSUER, 'imani']] };
    const unlocked = parseVoucherSecret(JSON.stringify(['VOUCHER', body]));
    const locked = parseVoucherSecret(JSON.stringify(['P2PK_VOUCHER', body]));

    expect(toHex(voucherCanonicalBytes(unlocked!))).not.toBe(toHex(voucherCanonicalBytes(locked!)));
  });
});

describe('parsing a hostile secret', () => {
  it('reads the lock key from data only for the locked kind', () => {
    const locked = parseVoucherSecret(
      JSON.stringify(['P2PK_VOUCHER', { nonce: 'n', data: '02ab', tags: [[VOUCHER_TAGS.VOUCHER_ID, 'v-1']] }])
    );
    const unlocked = parseVoucherSecret(JSON.stringify(['VOUCHER', { nonce: 'n', data: 'v-1', tags: [] }]));

    expect(locked?.lockKey).toBe('02ab');
    expect(locked?.voucherId).toBe('v-1');
    // A VOUCHER secret's `data` is a voucher id, not a key. Reporting it as a
    // lock key would be a type confusion that silently never matches a pubkey.
    expect(unlocked?.lockKey).toBeNull();
    expect(unlocked?.voucherId).toBe('v-1');
  });

  it.each([
    ['not json', 'not json'],
    ['empty', ''],
    ['a bare object', '{}'],
    ['wrong arity', '["P2PK_VOUCHER"]'],
    ['an unknown kind', '["P2PK",{"nonce":"n","data":"02ab","tags":[]}]'],
    ['a null body', '["P2PK_VOUCHER",null]'],
    ['an array body', '["P2PK_VOUCHER",[]]'],
    ['a missing data field', '["P2PK_VOUCHER",{"nonce":"n","tags":[]}]'],
    ['a non-string data field', '["P2PK_VOUCHER",{"nonce":"n","data":5,"tags":[]}]'],
    ['a non-array tags field', '["P2PK_VOUCHER",{"nonce":"n","data":"02ab","tags":"x"}]'],
    ['an empty tag', '["P2PK_VOUCHER",{"nonce":"n","data":"02ab","tags":[[]]}]'],
    ['a nested tag value', '["P2PK_VOUCHER",{"nonce":"n","data":"02ab","tags":[["a",{}]]}]'],
  ])('returns null rather than throwing on %s', (_label, input) => {
    // Every byte here is attacker-controlled: this runs on a credential from a
    // login request. A thrown parse error would be both an availability problem
    // and an oracle distinguishing malformed from merely wrong.
    expect(() => parseVoucherSecret(input)).not.toThrow();
    expect(parseVoucherSecret(input)).toBeNull();
  });

  it('rejects a secret carrying the same tag twice, as cashu-lib does', () => {
    // NUT-11 calls a repeated tag malformed, and `cashu-lib` enforces that
    // (`requireEachTagAtMostOnce`). Reading the first occurrence instead -- the
    // original behaviour here -- would let a doctored secret verify on this
    // side while the mint refuses it outright, since the issuer signature
    // covers both copies. NAP would grant a session from a document with two
    // answers.
    const doctored = JSON.stringify([
      'P2PK_VOUCHER',
      {
        nonce: 'n',
        data: '02ab',
        tags: [
          [VOUCHER_TAGS.EXPIRES_AT, '2000000000'],
          [VOUCHER_TAGS.EXPIRES_AT, '1'],
        ],
      },
    ]);

    expect(parseVoucherSecret(doctored)).toBeNull();
  });

  it('still accepts a tag key that merely repeats a *value*', () => {
    // The rule is one occurrence per key, not per value. Without this, the
    // check could be written as a value-set and would reject legitimate
    // secrets whose distinct tags happen to share a value.
    const fine = JSON.stringify([
      'P2PK_VOUCHER',
      {
        nonce: 'n',
        data: '02ab',
        tags: [
          [VOUCHER_TAGS.ISSUER, 'imani'],
          [VOUCHER_TAGS.UNIT, 'imani'],
        ],
      },
    ]);

    expect(parseVoucherSecret(fine)).not.toBeNull();
  });

  it('accepts a numeric tag written as a bare JSON number', () => {
    const parsed = parseVoucherSecret(
      JSON.stringify(['P2PK_VOUCHER', { nonce: 'n', data: '02ab', tags: [[VOUCHER_TAGS.EXPIRES_AT, 2_000_000_000]] }])
    );

    expect(parsed?.expiresAt).toBe(2_000_000_000);
    // And it renders identically to the string form, so a sender's choice of
    // JSON type cannot change what the signature covers.
    expect(new TextDecoder().decode(voucherCanonicalBytes(parsed!))).toContain('["expires_at",2000000000]');
  });
});

/**
 * The extension spec's §5.2 options block, checked against the real interface.
 *
 * §5.2 is the normative description of how a server wires this resolver, and it
 * had drifted completely: every field name in it named something that does not
 * exist, because it was written before the implementation and never revisited.
 * Nothing caught that — `docsTypecheck` covers the README and integration
 * guide, not the extension spec.
 *
 * Compared on key sets rather than by type-checking the block, because the
 * block is documentation prose with `REQUIRED` comments and illustrative
 * shapes; the property that has to hold is that it names the options that
 * actually exist, and all of them.
 */
describe('extension spec §5.2 matches VoucherAclResolverOptions', () => {
  const SPEC = resolve(
    dirname(fileURLToPath(import.meta.url)),
    '../../../docs/extensions/0001-voucher-bound-authorization.md'
  );

  /** Option names the spec's `VoucherAclResolverOptions` block declares. */
  function documentedOptions(): string[] {
    const doc = readFileSync(SPEC, 'utf8');
    const start = doc.indexOf('export interface VoucherAclResolverOptions {');

    expect(start, '§5.2 should declare VoucherAclResolverOptions').toBeGreaterThan(-1);

    const block = doc.slice(start, doc.indexOf('\n}', start));

    // `name:` for fields and `name(` for the method form `grant()`.
    return [...block.matchAll(/^ {2}([a-zA-Z]+)\??[:(]/gm)].map((match) => match[1]!);
  }

  it('documents every option the implementation accepts, and no others', () => {
    // Kept as a literal list rather than derived from the type: a type-level
    // comparison would need the options interface at runtime, and this is the
    // one place where writing the names out is the point.
    const actual = [
      'mintAllowlist',
      'issuerAllowlist',
      'mintClient',
      'availability',
      'grant',
      'permissionRegistry',
      'onMissingCredential',
      'fallback',
      'clock',
      'auditLogger',
    ];

    expect(new Set(documentedOptions())).toEqual(new Set(actual));
  });
});
